### ISSUE TITLE
Database does not contain skill with ID 440

### ISSUE THREAD

**Issue by Xyphien** [SomeFire/RPG-Maker-MV-Skill-Trees-System#30]
<img width="533" alt="image" src="https://github.com/SomeFire/RPG-Maker-MV-Skill-Trees-System/assets/48410556/aa9c0313-67d6-4f3d-b048-8a3c3f56e859">

**Comment by SomeFire** [comment]
As error saying, you don't have skill in database. Check RPG Maker skills, skill with number 440 is missed.

**Comment by Xyphien** [comment]
Awesome thanks! Now time to bash my head at what I'm actually trying to do. Do you have any plans to add a video tutorial?

**Comment by SomeFire** [comment]
No, I have no plans for video tutorials.
